// <auto-generated />
namespace Otel_Rezervasyon_Sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class DB6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB6));
        
        string IMigrationMetadata.Id
        {
            get { return "201910280008163_DB6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
