// <auto-generated />
namespace Otel_Rezervasyon_Sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class aasd12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aasd12));
        
        string IMigrationMetadata.Id
        {
            get { return "201910302235598_aasd12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
