// <auto-generated />
namespace Otel_Rezervasyon_Sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class db3333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db3333));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300022549_db3333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
