// <auto-generated />
namespace Otel_Rezervasyon_Sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _5464232 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5464232));
        
        string IMigrationMetadata.Id
        {
            get { return "201910310039581_5464232"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
