// <auto-generated />
namespace Otel_Rezervasyon_Sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class db333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db333));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300013453_db333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
